name: Tests

on:
  push:
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Run unit tests
        run: python -m unittest discover -s tests -p "test*.py" -q

